### ISSUE TITLE
Does the library support various data types?

### ISSUE THREAD

**Issue by appkr** [siara-cc/sqlite_blaster#4]
Hi, thanks for sharing the great library.

We are a logistics company located in Korea, and are very much interested in your project.
The fact is that we provides SQLite database(which contains mailing addresses of Korea) for portable devices, so that it can boot performance in searching for an address. The SQLite databases are all different device by device, and we have to make them on the fly... That is the reason why we are trying to use your library(insert speed).

A question arose while evaluating your project. As I wrote in the title, does this library support various SQL data types? The following is the example of table structure that we are going to use.

```shell
sqlite> PRAGMA table_info(test_schema);
0|id|VARCHAR(255)|1||0
1|string_column|VARCHAR(40)|1||0
2|tinyint_column|TINYINT(3)|1||0
3|int_column|INT(10)|1||0
4|text_column|TEXT|0||0
5|decimal_column|DECIMAL(10, 8)|1||0
```

Hope to have your answer, and thanks in advance...

**Comment by siara-cc** [comment]
Hi, yes this lib supports creating columns with different data types. Please refer to [example given in README](https://github.com/siara-cc/sqlite_blaster/blob/main/README.md#creating-a-regular-table).

Please also note that this library is for creating huge [clustered indices](https://www.sqlite.org/withoutrowid.html) and not for making regular sqlite database with multiple tables and indices.  Please check limitations section too.

**Comment by appkr** [comment]
Thanks for quick reply. I should have read the docs throughly, my bad. I'll read it again. We are not going to use clustered indices, so the library fits our needs.
